CREATE TABLE `master_tssim_scores` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL,
  `simulation_attempt` smallint(5) unsigned NOT NULL,
  `gs_follow_up_raw_score` decimal(5,2) DEFAULT NULL,
  `gs_motivational_fit_planning_and_organizing_raw_score` decimal(5,2) DEFAULT NULL,
  `gs_motivational_fit_decision_making_raw_score` decimal(5,2) DEFAULT NULL,
  `gs_follow_up_modified_score` decimal(5,2) DEFAULT NULL,
  `gs_motivational_fit_planning_and_organizing_modified_score` decimal(5,2) DEFAULT NULL,
  `gs_motivational_fit_decision_making_modified_score` decimal(5,2) DEFAULT NULL,
  `gs_motivational_fit_combined_modified_score` decimal(5,2) DEFAULT NULL,
  `gs_score` decimal(5,2) DEFAULT NULL,
  `gs_score_num_diamonds` tinyint(3) unsigned DEFAULT NULL,
  `behavioral_questions_attempts_count` tinyint(3) unsigned NOT NULL,
  `behavioral_questions_score` decimal(5,2) DEFAULT NULL,
  `behavioral_questions_score_num_diamonds` tinyint(3) unsigned DEFAULT NULL,
  `follow_up_questions_attempts_count` tinyint(3) unsigned NOT NULL,
  `follow_up_questions_score` decimal(5,2) DEFAULT NULL,
  `follow_up_questions_score_num_diamonds` tinyint(3) unsigned DEFAULT NULL,
  `motivational_fit_questions_attempts_count` tinyint(3) unsigned NOT NULL,
  `motivational_fit_questions_score` decimal(5,2) DEFAULT NULL,
  `motivational_fit_questions_score_num_diamonds` tinyint(3) unsigned DEFAULT NULL,
  `candidate_experience_score` decimal(5,2) unsigned DEFAULT NULL,
  `candidate_experience_score_num_diamonds` tinyint(3) unsigned DEFAULT NULL,
  `start_datetime` datetime NOT NULL,
  `end_datetime` datetime NOT NULL,
  `moving_through_the_interview_time` varchar(12) COLLATE utf8_bin NOT NULL,
  `moving_through_the_interview_time_num_diamonds` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id_simulation_attempt_index` (`user_id`,`simulation_attempt`) USING HASH
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

